### ISSUE TITLE
Version 1.94 isn't connecting

### ISSUE THREAD

**Issue by nicocesar** [greenaddress/GreenBits#197]
Update happened overnight and the connection icon is there but it doesn't connect. Is there a way to debug of what's actually trying to do?

**Comment by 5chdn** [comment]
My wallet, version 1.93 also does not connect.

> Not connected, connection will resume automatically.

**Comment by nicocesar** [comment]
I downgraded to 1.93 and same thing.  Maybe the endopoint is down ?  
is this wss://prodwss.greenaddress.it/v2/ws/ .... ? taken from 
https://github.com/greenaddress/GreenBits/blob/master/app/src/production/java/com/greenaddress/greenapi/Network.java#L7

**Comment by greenaddress** [comment]
Hi @nicocesar, one way to debug is to enable developer mode in the phone and then provide adb logs (I can provide more precise instructions if you want).

Did you enable Socks5 proxy? Are you connected to Wifi or 4G? Android version?

@5chdn @nicocesar version 1.93 unfortunately will no longer work (unless you disable certificate pinning manually in the code) so you'll have to upgrade back to 1.94 (or use the desktop chrome app while we figure out what the problem above is)

**Comment by nicocesar** [comment]
@greenaddress I upgraded to 1.94 (@5chdn I recommend to do the same ) then re-enter my passphrase selected my pin and had all the funds. Was this a endpoint problem? 

From my point of view this issue is resolved for me but it could be transformed to "giving users a better error reporting tools when service is unavailable".  Or just a simple "status page" like many services when the for the service is experiencing turbulence

**Comment by 5chdn** [comment]
@greenaddress my F-Droid does not show any upgrade yet. Have to wait then.

**Comment by greenaddress** [comment]
@nicocesar thanks for the confirmation!

Not sure what the problem was with 1.94 when it didn't work but doesn't seem the backend/endpoint, maybe unstable connectivity? We're working to improve the error reporting and the status page idea is indeed good so we'll look into that.

@5chdn F-Droid will probably fail to build it because it is set for master, we'll look into addressing that, meanwhile you can fetch 1.94 signed by us from here https://github.com/greenaddress/GreenBits/releases/tag/r1.94

**Comment by nicocesar** [comment]
connectivity is pretty stable here 

I can't send after logged in, see https://github.com/greenaddress/GreenBits/issues/198  

that definitely looks like a backend problem ...  I can send you a screenshot privately with details

**Comment by 5chdn** [comment]
neither f-droid nor manually installing 1.94 from apk here does work on my cyanogenmod 13.1, i'm a bit clueless how to get greenbits to work in future. just started to like it. however, the installed 1.93 doesn't work anymore.

why isnt it possible to use the wallet in offline mode anyways?

**Comment by jgriffiths** [comment]
@5chdn, the wallet requires connectivity with the GA backend servers in order to do anything useful. The only thing that could be done in offline mode would perhaps to recover nlocktime funds like the gentle tool does (we may roll this functionality into GreenBits at some point in the future).

With regards to your problems connecting, is it possible for you give some more details? e.g. have you changed the default settings? What behaviour exactly are you seeing? Do you see a plug icon on the login screen? Does the testnet version of the app work for you? Is it possible for you to enable adb logging and send us an adb log?

Please open a new issue for your problem (with as much information as possible) if it remains unresolved.
