### ISSUE TITLE
Preload receive address and cache

### ISSUE THREAD

**Issue by greenaddress** [greenaddress/GreenBits#215]
Rather than loading an address each time one moves to the "Receive" tab we should fetch one as soon as we login and show that one on Receive (while also prefetching in the background the next one)

We should only do so if:
- Segwit is not enabled server side
- Segwit is enabled server side and user has activated it

If not used the address should be cached client side for the next time (ideally not in clear text)

**Comment by jgriffiths** [comment]
Fixed in 65b8042310a617ee10e6b74fce3183ad50bd2842. Note that we do not do any special handling of segwit, since:

- Only addresses generated for display are cached, tx construction addresses (change) are always made by new calls.
- The address data contains the address type
- Segwit can be activated and locked by another client anyway, so it is always possible to have segwit enabled with a cached non-SW address.

We should verify that post SW activation for a user, the cached address can receive funds.
