### ISSUE TITLE
Use BIP49 for SegWit addresses

### ISSUE THREAD

**Issue by prusnak** [greenaddress/GreenBits#269]
TREZOR and Ledger use BIP49 path for generating SegWit addresses. It would be great if GreenBits followed the suite.

See: https://github.com/bitcoin/bips/blob/master/bip-0049.mediawiki

TL;DR just replace 44 with 49 in derivation path for SegWit.

**Comment by jgriffiths** [comment]
Hi,

As a multisig wallet BIP44/49 are not useful to GreenAddress. In order to ensure that the service uses keys unique to each user (for privacy and to avoid using the same path in multiple unrelated txs, potentially identifying GreenAddress txs) we derive a new top level path for each user.

The main advantage of these BIPs is that private keys cans be imported between wallets, which is not possible with our multisig. As such it is unlikely we will every support either BIP.

**Comment by prusnak** [comment]
Ah, sorry, I got confused. I thought 3-address meant SegWit, not
multisig, and I thought GreenBits is not a miltisig wallet. Thanks for
clarification.
