### ISSUE TITLE
Display info message when disabling SegWit is not possible

### ISSUE THREAD

**Issue by Nephiel** [greenaddress/GreenBits#286]
Once a SegWit address has been generated for a given wallet, it is no longer possible to disable SegWit for that wallet.

If the user tries to disable SegWit in such a case, GreenBits simply does nothing.
GreenBits should probably display a toast to inform the user of the reason that SegWit cannot be disabled, just like the web and Chrome versions of GreenAddress already do.

**Comment by jgriffiths** [comment]
Hi,

Thanks for the report. This is a known issue with Android where the default style of disabled preference items is indistinguishable from enabled ones (even down to how they react to touches). We plan to address it soon by adding hint text to all items that are disabled indicating why. In the specific case of segwit we may possibly just the hide the option once it is no longer possible to use it, since it just clutters the UI at that point.

**Comment by jgriffiths** [comment]
In the next (GDK-based) release, disabling segwit will not be possible, so closing this.
