### ISSUE TITLE
Display satoshis per byte not only in custom

### ISSUE THREAD

**Issue by jtimon** [greenaddress/GreenBits#288]
The priority selection allows high, normal, low, economy, custom and instant.
Except for custom which shows you the satoshis per virtual byte, the selections are vague into what they mean exactly. Even if only custom allows the user to edit the satoshis per vbyte, it could at least show it. That way the user could rapidly get an idea of what each of them mean in terms of sat/vbyte just by going through them before sending

Actually, custom uses satoshis/kbyte. perhaps satoshis per byte would be better.

**Comment by jgriffiths** [comment]
Good suggestion, thanks!

In the near term we want the transaction construction (past destination address selection at least) to be dynamic, i.e. the user should be able to choose the fee and have the summary updated not just with the fee rate but the total fee given the size of the tx. This is needed for adding coin control but also to improve hardware wallet signing so that we can show e.g. the change address before the user is prompted to sign on device.

Once our current h/w wallet changes are merged we will take a look at this.

**Comment by leafcutterant** [comment]
Any updates on this?

I agree with @jtimon - high/normal/low/economy/instant are relative and thus meaningless in themselves. It would make much more sense if the wallet would also display the expected delay in blocks and the actual fee that belongs to the option, e.g.:

`normal (in 2-3 blocks, 30 sat/byte)`

This would give the user a better ground to discover their preference.

And I too advocate for a switch to satoshi/byte, or at least an option to choose this fee denomination. Most estimation services use sat/b. It's a pain in the ass to calculate with sat/kB.

**Comment by jgriffiths** [comment]
Implemented in the next (GDK-based) release. We now use sat/vbyte everywhere, and have time based fee buttons with the fee and fee rate shown.
