### ISSUE TITLE
fee cut in half

### ISSUE THREAD

**Issue by riclas** [greenaddress/GreenBits#295]
i'm not sure if this is a problem with only custom fees or also with the other fee options.
I was trying out greenbits today and sent a transaction where i put 270000 sat/Kb as my custom fee.
That fee was cut in half on the transaction, here is the hash: fbbaa43c51ee75441e5e787e45a3cbbaf898b7e19768191f9cc052eb0536b7b1

I believe this is a problem related to segwit enabled transactions, because a friend of mine reported the same issue on his Ledger wallet, while this never happened to him before the upgrade of the wallet.

Also, please change the display to sat/B :)

**Comment by jgriffiths** [comment]
Hi,

From core, dumping the resulting transaction gives:
  "size": 667,
  "vsize": 337,

from https://blockexplorer.com/tx/fbbaa43c51ee75441e5e787e45a3cbbaf898b7e19768191f9cc052eb0536b7b1 the fee is 91530 satoshi.

This gives a fee rate of 91530/337 which is 271.6 satoshis per vbyte as this is a segwit transaction. The difference from your 270 sat/byte requested is due to +/-1 byte per signature in the final signed transaction.

Miners accept segwit txs based on the discounted vsize, so the current behavior is correct.

**Comment by riclas** [comment]
I now understand why the fee is what it is, but then it becomes a usability issue. Greenbits shows "fee/size (bytes)/fee per Kb 0.00091530 / 667 / 0.00137227". Either change size to vbytes or on the custom fee screen "fee per vKb".
And if you go for the latter, no user will understand what it means, and people who see fees on any block explorer in sat/b will be confused like i was. By your logic all explorers are showing the fee rate wrong, including smartbit, the one greenbits uses.

**Comment by jgriffiths** [comment]
Hi,

We plan to change the transaction list to show the fee/vbyte but this requires a database migration on the backend which needs to be carefully planned/deployed. For bumpable/unconfirmed transactions we have fixed the display on the transaction details bump screen already.

Core only considers fee/vsize now, for non-segwit transactions vsize=size. Block explorers *are* showing this incorrectly currently but we expect them to switch in the future.

**Comment by riclas** [comment]
IMHO this route will alienate users that came to greenbits looking for a segwit enabled wallet with custom fees (granted this is probably a small portion of the userbase, but still...)
I'm not sure why you don't just use the fee/size until you update your backend, but that's your choice.

/end
