### ISSUE TITLE
Showing mnemonic should require 2FA when enabled

### ISSUE THREAD

**Issue by Transisto** [greenaddress/GreenBits#303]
Someone can just show the mnemonic and sidestep 2FA altogether.

Same thing with the PIN, when a PIN is set it's not asking for it before showing the mnemonic.

For the business use I have I'd actually need a separate password to enabling showing the mnemonic.

I want to limit access to the bitcoin to this physical device.

**Comment by jgriffiths** [comment]
Hi,

You can't see the mnemonic in watch only mode, and you can only see the mnemonic if you are logged into the wallet (which requires the mnemonic or PIN).

If you have access to the logged in wallet you don't need the mnemonic, you can just send the coins. Having the mnemonic does not sidestep 2fa in any way, you still have to pass 2fa auth in order to move coins.

I'm closing this, feel free to explain in more detail if you believe the above is incorrect.
