### ISSUE TITLE
pin confirmation

### ISSUE THREAD

**Issue by anarcat** [greenaddress/GreenBits#58]
it seems to me it would be important to have a two step process for the PIN entry. as it is now, the first time I used this, it was totally unclear i was setting something i could not change later (#57) nor what it was for or how secure it should be...

**Comment by greenaddress** [comment]
What do you mean by two step process? It is not a big problem if the user forgets the pin or gets it wrong, the important thing is that they keep a backup of their mnemonics in a safe place.

We can add a way to change the PIN as per issue #57 (currently you'd have to get it wrong 3 times, then login with mnemonics and set a new PIN, which can be quite painful as you said)

**Comment by anarcat** [comment]
I mean having to enter the pin twice to make sure the user didn't make a mistake.

On my first setup, I couldn't log back in to the app after the timeout because i somehow mis-entered the thing (and obviously, I skipped the backup step, thinking "oh i'll do *that*" later). The result was harmless: there was nothing in the account, but I ended up creating a few accounts like this, because the second time I created an account with a weak PIN just to get through and get something done. :)

**Comment by greenaddress** [comment]
In this case it is my opinion that before we make the pin setup twice as long we concentrate on disincentivizing the 'oh i'll do that later' because the PIN is not a reliable system, doesn't work on other devices unless setup from scratch with a mnemonic, etc and you can always lose the phone or have it damaged.

We should make sure users don't go easy on the mnemonic steps; this would solve this problem from the get go too.

Thoughts?

**Comment by anarcat** [comment]
I think a good effort was made to disincentivize. I am not sure what more can be done - users will always disobey.

This is a different issue: i was *expecting* a PIN confirmation dialog.

**Comment by greenaddress** [comment]
Fair enough; I'll look into adding one.

**Comment by jgriffiths** [comment]
We have now merged a PIN confirmation dialog for PIN setup, closing.
